#include <iostream>
class myclass{
    public:
    //this case no use of constructor, because we are not initializing any member variables in this class. The default constructor will be automatically generated by the compiler, and it will be used to create instances of myclass without any explicit initialization.
    int x,y;
    void display(){
        std::cout<<"x: "<<x<<", y: "<<y<<std::endl;
    }
};
class myclass2{
    public:
    //this case we are using constructor to initialize member variables x and y. The constructor takes two parameters, a and b, which are used to set the values of x and y respectively. When an instance of myclass2 is created, the constructor is called automatically, and the member variables are initialized with the provided values.
    int x,y;
    myclass2(int a,int b){
        x=a;
        y=b;
    }
    void display(){
        std::cout<<"x: "<<x<<", y: "<<y<<std::endl;
    }
};
class myclass3{
    public:
    //this is the case of default constructor deletion, as cpp provides default constructor if we don't provide any constructor, but in this case we are deleting the default constructor, so we cannot create an instance of myclass3 without providing any arguments. If we try to create an instance of myclass3 without providing any arguments, we will get a compilation error.
    myclass3() = delete; // Delete the default constructor
    int x,y;
    myclass3(int a,int b){
        x=a;
        y=b;
    }
    void display(){
        std::cout<<"x: "<<x<<", y: "<<y<<std::endl;
    }
};
int main(){
    //output for c1 will be garbage values for x and y, because we are not initializing them in the constructor or anywhere else. The default constructor is automatically generated by the compiler, but it does not initialize the member variables, so they will contain whatever values happen to be in memory at that location.
    myclass c1;
    c1.display();

    myclass2 c2(10,20);
    c2.display();

    //myclass3 c3; // This will cause a compilation error because the default constructor is deleted
    myclass3 c4(30,40);
    c4.display();
    return 0;
}